# Generated by Django 4.0.2 on 2022-02-15 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0002_alter_hotel_star_rating_usersratinghotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_rating_for_hotel',
        ),
        migrations.RemoveField(
            model_name='usersratinghotel',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='overall_rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TaskNum1.usersratinghotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersratinghotel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
