# Generated by Django 4.0.2 on 2022-02-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0003_remove_user_user_rating_for_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersratinghotel',
            name='rating_from_user_for_hotel',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
