# Generated by Django 4.0.2 on 2022-02-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0005_alter_hotel_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersratinghotel',
            name='hotels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TaskNum1.hotel'),
            preserve_default=False,
        ),
    ]
