# Generated by Django 4.0.2 on 2022-02-15 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0007_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersratinghotel',
            name='hotels',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TaskNum1.hotel'),
        ),
        migrations.AlterField(
            model_name='usersratinghotel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
