# Generated by Django 4.0.2 on 2022-02-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0009_alter_hotel_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='overall_rating',
        ),
    ]
