# Generated by Django 4.0.2 on 2022-02-16 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0010_remove_hotel_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='room_description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Описание слишком большое,максимально количество слов 100')]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
