# Generated by Django 4.0.2 on 2022-02-16 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0011_alter_hotel_room_description_alter_hotel_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='room_description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=2, message='Описание слишком большое,максимально количество слов 100')]),
        ),
    ]
