# Generated by Django 4.0.2 on 2022-02-16 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0012_alter_hotel_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Для создания отеля,требуется хотябы 1 фото')]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_for_room',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='Извините но это слишком большая сумма')]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Описание слишком большое,максимально количество слов 100'), django.core.validators.MinValueValidator(limit_value=20, message='Минимальное количество слов описания, 20')]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(limit_value=50, message='Название слишком большое')]),
        ),
    ]
