# Generated by Django 4.0.2 on 2022-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0013_alter_hotel_photo_alter_hotel_price_for_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_for_room',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
