# Generated by Django 4.0.2 on 2022-02-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0018_alter_hotel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
