# Generated by Django 4.0.2 on 2022-02-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0019_alter_hotel_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
