# Generated by Django 4.0.2 on 2022-02-16 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0020_alter_hotel_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.CharField(max_length=51, validators=[django.core.validators.MaxLengthValidator(limit_value=50, message='Название слишком большое')]),
        ),
    ]
