# Generated by Django 4.0.2 on 2022-02-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0023_alter_hotel_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_for_room',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
