# Generated by Django 4.0.2 on 2022-02-16 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0036_alter_hotel_price_for_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_for_room',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(inverse_match=False, message='Неверный формат введенной цены', regex='^[-+]?[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=50, message='Название слишком большое')]),
        ),
    ]
