# Generated by Django 4.0.2 on 2022-02-16 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0037_alter_hotel_price_for_room_alter_hotel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_for_room',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(inverse_match=False, message='Неверный формат введенной цены', regex='^[-+]?[0-9]+$')]),
        ),
    ]
