# Generated by Django 4.0.2 on 2022-02-16 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskNum1', '0038_alter_hotel_price_for_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Прикрепите хотябы 1 изображение')]),
        ),
    ]
